### ISSUE TITLE
Error loading logo in README

### ISSUE THREAD

**Issue by kotleni** [0x78654C/xTerminal#16]
Error loading image in README:
<img width="471" alt="Снимок экрана 2021-11-01 в 17 55 19" src="https://user-images.githubusercontent.com/38311102/139701252-ad48bc32-59d9-4d19-a514-e6dfeaafb27f.png">

from: [commit](https://github.com/0x78654C/xTerminal/commit/fa5cf307890ee517110b0b5dbb7c2c5f64979663)
browser: Safari
os: MacOS

How to fix: convert bmp to png.

**Comment by 0x78654C** [comment]
check now if is fine

**Comment by kotleni** [comment]
Yeah, all okay!
